apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: kubectl-apps-version
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/icyd/kubectl-apps-version/releases/download/v0.1.0/kubectl-apps-version_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./kubectl-apps-version"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-apps-version"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/icyd/kubectl-apps-version/releases/download/v0.1.0/kubectl-apps-version_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./kubectl-apps-version"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-apps-version"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/icyd/kubectl-apps-version/releases/download/v0.1.0/kubectl-apps-version_windows_amd64.zip
    sha256: ""
    files:
    - from: "/kubectl-apps-version.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-apps-version.exe"
  shortDescription: A new plugin
  homepage: https://github.com/icyd/kubectl-apps-version
  caveats: |
    Usage:
      $ kubectl appsversion

    For additional options:
      $ kubectl appsversion --help
      or https://github.com/icyd/kubectl-apps-version/blob/v0.1.0/doc/USAGE.md

  description: |
    Plugin to get applications' (deployments, statefulsets, daemonsets) container images versions.
